-- V001: Create users table with email-only authentication
CREATE TABLE users (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       email CHARACTER VARYING(255) NOT NULL UNIQUE,
                       password CHARACTER VARYING(255) NOT NULL,
                       first_name CHARACTER VARYING(50) NOT NULL,
                       last_name CHARACTER VARYING(50) NOT NULL,
                       created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_created_at ON users(created_at);

-- Constraints
ALTER TABLE users ADD CONSTRAINT check_first_name_length
    CHECK (LENGTH(first_name) >= 1 AND LENGTH(first_name) <= 50);

ALTER TABLE users ADD CONSTRAINT check_last_name_length
    CHECK (LENGTH(last_name) >= 1 AND LENGTH(last_name) <= 50);