-- V002: Create workouts table
CREATE TABLE workouts (
                          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          workout_name CHARACTER VARYING(255) NOT NULL,
                          workout_description TEXT,
                          workout_category CHARACTER VARYING(255) NOT NULL,
                          is_cardio BOOLEAN DEFAULT false,
                          image_url CHARACTER VARYING(255),
                          created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX idx_workouts_category ON workouts(workout_category);
CREATE INDEX idx_workouts_cardio ON workouts(is_cardio);