-- V003: Create workout log table
CREATE TABLE workout_log (
                             id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                             user_id BIGINT NOT NULL,
                             workout_id BIGINT NOT NULL,
                             date DATE NOT NULL,
                             notes TEXT,
                             created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Foreign key constraints
ALTER TABLE workout_log
    ADD CONSTRAINT fk_workout_log_user_id
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE workout_log
    ADD CONSTRAINT fk_workout_log_workout_id
        FOREIGN KEY (workout_id) REFERENCES workouts(id) ON DELETE CASCADE;

-- Indexes for performance
CREATE INDEX idx_workout_log_user_id ON workout_log(user_id);
CREATE INDEX idx_workout_log_workout_id ON workout_log(workout_id);
CREATE INDEX idx_workout_log_date ON workout_log(date);
CREATE INDEX idx_workout_log_user_date ON workout_log(user_id, date);