-- V004: Create performance records table
CREATE TABLE performance_records (
                                     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                     workout_log_id BIGINT NOT NULL,
                                     set_number INTEGER,
                                     reps INTEGER,
                                     weight DOUBLE PRECISION,
                                     duration_minutes INTEGER,
                                     duration_seconds DOUBLE PRECISION,
                                     distance_km DOUBLE PRECISION,
                                     calories_burned INTEGER,
                                     notes CHARACTER VARYING(255),
                                     created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Foreign key constraint
ALTER TABLE performance_records
    ADD CONSTRAINT fk_performance_records_workout_log_id
        FOREIGN KEY (workout_log_id) REFERENCES workout_log(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX idx_performance_records_workout_log_id ON performance_records(workout_log_id);
CREATE INDEX idx_performance_records_created_at ON performance_records(created_at);