-- V006: Create exercise library tables
CREATE TABLE exercises (
                           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           name CHARACTER VARYING(255) NOT NULL,
                           goal CHARACTER VARYING(100),
                           duration CHARACTER VARYING(100),
                           equipment CHARACTER VARYING(100),
                           difficulty CHARACTER VARYING(50),
                           calories CHARACTER VARYING(50),
                           emoji CHARACTER VARYING(10),
                           description TEXT,
                           video_url CHARACTER VARYING(500),
                           published BOOLEAN DEFAULT false,
                           created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Exercise benefits table
CREATE TABLE exercise_benefits (
                                   exercise_id BIGINT NOT NULL,
                                   benefits CHARACTER VARYING(255),
                                   CONSTRAINT fk_exercise_benefits_exercise_id
                                       FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
);

-- Exercise tips table
CREATE TABLE exercise_tips (
                               exercise_id BIGINT NOT NULL,
                               tips CHARACTER VARYING(255),
                               CONSTRAINT fk_exercise_tips_exercise_id
                                   FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
);

-- Indexes for performance and filtering
CREATE INDEX idx_exercises_goal ON exercises(goal);
CREATE INDEX idx_exercises_difficulty ON exercises(difficulty);
CREATE INDEX idx_exercises_equipment ON exercises(equipment);
CREATE INDEX idx_exercises_published ON exercises(published);
CREATE INDEX idx_exercises_name ON exercises(name);
CREATE INDEX idx_exercise_benefits_exercise_id ON exercise_benefits(exercise_id);
CREATE INDEX idx_exercise_tips_exercise_id ON exercise_tips(exercise_id);